background_opacity: 0.9

# Colors (Paper Theme) https://github.com/s6muel/paper-theme/blob/main/themes/alacritty/paper-theme.yml
colors:
  # Default colors
  primary:
    background: "#F2EEDE"
    foreground: "#000000"

  # Normal colors
  normal:
    black: "#000000"
    red: "#CC3E28"
    green: "#216609"
    yellow: "#B58900"
    blue: "#1E6FCC"
    magenta: "#5C21A5"
    cyan: "#158C86"
    white: "#AAAAAA"

  # Bright colors
  bright:
    black: "#555555"
    red: "#CC3E28"
    green: "#216609"
    yellow: "#B58900"
    blue: "#1E6FCC"
    magenta: "#5C21A5"
    cyan: "#158C86"
    white: "#AAAAAA"
