# 色はデフォが綺麗なのでデフォにする
# https://github.com/alacritty/alacritty-theme?tab=readme-ov-file
# [colors.bright]
# black = "0x808080"
# blue = "0x0066ff"
# cyan = "0x00ffff"
# green = "0x33ff00"
# magenta = "0xcc00ff"
# red = "0xfe0100"
# white = "0xFFFFFF"
# yellow = "0xfeff00"

[colors.cursor]
cursor = "0xffffff"
text = "0xF81CE5"

# [colors.normal]
# black = "0x000000"
# blue = "0x0066ff"
# cyan = "0x00ffff"
# green = "0x33ff00"
# magenta = "0xcc00ff"
# red = "0xfe0100"
# white = "0xd0d0d0"
# yellow = "0xfeff00"

[colors.primary]
background = "0x2e2e2e"
foreground = "0xdedede"

[font.normal]
family = "UDEV Gothic 35NF"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "F11"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "F12"

[mouse]
hide_when_typing = false

# [mouse.double_click]
# threshold = 300
#
# [mouse.triple_click]
# threshold = 300

[window.padding]
x = 12
y = 10
