[font.normal]
family = "UDEV Gothic 35NF"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Minus"
mods = "Command|Shift"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "Copy"
mods = "Shift"
mouse = "Left"

[[mouse.bindings]]
action = "Paste"
mods = "Shift"
mouse = "Right"


[shell]
args = ["--cd ~"]
program = "/Windows/System32/wsl.exe ~ -d Arch -u usuyuki"

[window]
opacity = 1.0
